name: Automation CI

on:
  workflow_dispatch:   # Manual trigger (like Jenkins "Build with Parameters")
    inputs:
      browser:
        description: 'Select the browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   # Use ubuntu runner

    env:
      COMPOSE_PATH: ${{ github.workspace }}
      BROWSER: ${{ github.event.inputs.browser || 'chrome' }}

    steps:
      # === Stage: Checkout (like Jenkins "Checkout") ===
      - name: Checkout Repository
        uses: actions/checkout@v3

      # === Stage: Start Selenium Grid via Docker ===
      - name: Start Selenium Grid via Docker
        run: |
          echo "Starting selenium grid with docker compose"
          docker-compose -f $COMPOSE_PATH/docker-compose.yml up -d
          echo "Waiting for Selenium Grid to be Ready..."
          sleep 30

      # === Stage: Setup JDK & Maven (similar to Jenkins tools block) ===
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # === Stage: Build & Test ===
      - name: Build & Run Tests
        run: mvn clean test -Dbrowser=${{ env.BROWSER }}

      # === Stage: Report (save allure results) ===
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results

      # === Stage: End Selenium Grid via Docker ===
      - name: Stop Selenium Grid via Docker
        if: always()
        run: |
          echo "Closing selenium grid with docker compose"
          docker-compose down
          sleep 10

      # === Post Actions: Email Notification (like Jenkins emailext) ===
      - name: Send Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Project: ${{ github.repository }} | Build #${{ github.run_number }} - ${{ job.status }}"
          to: "divyaranjan1995@gmail.com"
          from: "GitHub Actions <${{ secrets.EMAIL_USER }}>"
          content_type: text/html
          body: |
            <html>
            <body style="font-family: Arial, sans-serif; font-size: 14px; color: #333;">
              <p>Hello Team,</p>
              <p>The latest GitHub Actions build has completed. Please find the details below:</p>

              <table style="border-collapse: collapse; width: 100%; max-width: 600px;">
                <tr>
                  <td style="padding: 8px; font-weight: bold;">🛠 Project Name</td>
                  <td style="padding: 8px;">${{ github.repository }}</td>
                </tr>
                <tr style="background-color: #f9f9f9;">
                  <td style="padding: 8px; font-weight: bold;">🔢 Build Number</td>
                  <td style="padding: 8px;">#${{ github.run_number }}</td>
                </tr>
                <tr>
                  <td style="padding: 8px; font-weight: bold;">📜 Build Status</td>
                  <td style="padding: 8px; color: ${{ job.status == 'success' && 'green' || 'red' }};">
                    <b>${{ job.status }}</b>
                  </td>
                </tr>
                <tr style="background-color: #f9f9f9;">
                  <td style="padding: 8px; font-weight: bold;">🔗 Build URL</td>
                  <td style="padding: 8px;">
                    <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" style="color: #1a73e8;">Click here</a>
                  </td>
                </tr>
                <tr>
                  <td style="padding: 8px; font-weight: bold;">📜 Last Commit</td>
                  <td style="padding: 8px;">${{ github.sha }}</td>
                </tr>
                <tr style="background-color: #f9f9f9;">
                  <td style="padding: 8px; font-weight: bold;">📂 Branch</td>
                  <td style="padding: 8px;">${{ github.ref_name }}</td>
                </tr>
                <tr>
                  <td style="padding: 8px; font-weight: bold;">📎 Allure Report</td>
                  <td style="padding: 8px;">
                    (Download artifact: allure-results from this run)
                  </td>
                </tr>
              </table>

              <br>
              <p>Best regards,<br>
              <b>Automation Team</b></p>
            </body>
            </html>
