name: Learning GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      browser:
        description: Select the browser to execute the cases
        required: true
        type: choice
        default: 'chrome'
        options:
          - edge
          - chrome
          - firefox

      saveResult:
        description: Whether to save the build result
        required: true
        type: choice
        default: 'true'
        options:
          - true
          - false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'


